name: Actionlint

on:
    workflow_call:
        inputs:
            additional-files:
              required: false
              type: string
              default: ''

jobs:
    actionlint:
        name: Actionlint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Run actionlint
              uses: raven-actions/actionlint@v2
              with:
                  files: ".github/workflows/*.yml, ${{ inputs.additional-files }}"
