name: Sync labels

on:
  workflow_call:

jobs:
  sync-labels:
    name: Sync labels
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Sync labels
        uses: srealmoreno/label-sync-action@v2.0.0
        with:
          clean-labels: true
          config-file: https://raw.githubusercontent.com/RubberDuckCrew/.github/refs/heads/main/configs/conventions/labels.yml
