name: Close Actions

on:
  workflow_call:

jobs:
  close:
    name: Close issue or pull request
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Remove labels
        uses: IamPekka058/removeLabels@82c8d070189f04448d6ffe291a0e398c2a749a09 # v2
        with:
          github_token: ${{ github.token }}
          labels: "🚧 Work in Progress"

  close-pr:
    name: Close pull request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    permissions:
      actions: write

    steps:
      - name: Delete branch caches
        uses: Friedinger/DeleteBranchCaches@b4482bee8da523e175964cc328da4862593bec8e # v2.4.4
        with:
          github-token: ${{ github.token }}
          ref: "refs/pull/${{ github.event.pull_request.number }}/merge"
