name: Actionlint

on:
    pull_request:
        paths: [.github/workflows/**]

jobs:
    actionlint:
        uses: RubberDuckCrew/.github/configs/actions/actionlint@main
        with:
            additional-files: "configs/actions/**/*.yml"
