name: Actionlint

on:
    pull_request:
        paths: [.github/workflows/**]

jobs:
    actionlint:
        uses: RubberDuckCrew/.github/.github/workflows/action-actionlint.yml@main
        with:
            additional-files: "configs/actions/**/*.yml"
