name: Enforce conventions

on:
    pull_request:
        types: [opened, labeled, unlabeled, synchronize]

jobs:
    run:
        # uses: RubberDuckCrew/.github/.github/workflows/action-conventions.yml@main
        uses: ./.github/workflows/action-conventions.yml
        permissions:
            issues: write
            pull-requests: write
