name: Enforce conventions

on:
    pull_request_target:
        types: [opened, labeled, unlabeled, synchronize]

jobs:
    enforce-conventions:
        uses: RubberDuckCrew/.github/configs/actions/conventions.yml@main
