name: Enforce conventions

on:
    pull_request_target:
        types: [opened, labeled, unlabeled, synchronize]

jobs:
    enforce-conventions:
        uses: RubberDuckCrew/.github/.github/workflows/action-conventions.yml@main
