name: Build and deploy docs

on:
  push:
    branches: [main]
    paths: &paths
      - docs/**
      - .github/workflows/docs.yml
      - .github/workflows/action-docs.yml
  pull_request:
    types: [opened, labeled, synchronize]
    paths: *paths

jobs:
  run:
    # uses: RubberDuckCrew/.github/.github/workflows/action-docs.yml@main
    uses: ./.github/workflows/action-docs.yml
    with:
      project-name: rubberduckcrew
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    permissions:
      contents: read
      deployments: write
      pull-requests: write
