name: Sync labels

on:
    schedule:
        - cron: "0 3 * * 0"
    push:
        branches: [main]
        paths: [.github/workflows/sync-labels.yml]
    workflow_dispatch:

jobs:
    sync-labels:
        uses: RubberDuckCrew/.github/configs/actions/sync-labels@main
